[build]
  command = "npm run build:prod"
  publish = "dist"

[context.production]
  environment = { VITE_ENV = "production" }

[context.development]
  environment = { VITE_ENV = "development" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"